# Generated by Django 6.1.1 on 2026-09-08 10:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование подразделения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Тип оборудования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Материал/инструмент',
                'verbose_name_plural': 'Материалы/инструменты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование организации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OutsideLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Наименование (адрес)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Внешнее местоположение',
                'verbose_name_plural': 'Внешние местоположения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование сервиса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Отдел/лаборатория/цех/участок',
                'verbose_name_plural': 'Отделы/лаборатории/цехи/участки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование оборудования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='events.devicetype', verbose_name='Тип оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateTimeField(verbose_name='Планируемая дата и время начала работ')),
                ('planned_end', models.DateTimeField(verbose_name='Планируемая дата и время окончания работ')),
                ('planned_duration_days', models.IntegerField(default=0, verbose_name='Длительность (дни)')),
                ('planned_duration_hours', models.IntegerField(default=0, verbose_name='Длительность (часы)')),
                ('planned_duration_minutes', models.IntegerField(default=0, verbose_name='Длительность (минуты)')),
                ('work_reason', models.CharField(choices=[('avr', 'АВР'), ('planned', 'Плановые работы'), ('ppr', 'ППР')], max_length=20, verbose_name='Причина работ')),
                ('is_service_disruption', models.BooleanField(default=False, verbose_name='Нарушение сервиса')),
                ('service_disruption_duration_days', models.IntegerField(default=0, verbose_name='Длительность перерыва (дни)')),
                ('service_disruption_duration_hours', models.IntegerField(default=0, verbose_name='Длительность перерыва (часы)')),
                ('service_disruption_duration_minutes', models.IntegerField(default=0, verbose_name='Длительность перерыва (минуты)')),
                ('is_duration_match', models.BooleanField(default=False, verbose_name='Длительность работ совпадает с перерывом сервиса')),
                ('services_comment', models.TextField(blank=True, verbose_name='Комментарии к затронутым сервисам')),
                ('is_object_outside', models.BooleanField(default=False, verbose_name='Объект находится за территорией Общества')),
                ('is_work_outside', models.BooleanField(default=False, verbose_name='Работы выполняются за территорией Общества')),
                ('work_name', models.CharField(max_length=500, verbose_name='Наименование работ')),
                ('work_description', models.TextField(verbose_name='Подробное описание работ')),
                ('is_tech_card_required', models.BooleanField(default=False, verbose_name='Требуется технологическая карта')),
                ('materials_comment', models.TextField(blank=True, verbose_name='Комментарий к материалам')),
                ('revision_reason', models.TextField(blank=True, verbose_name='Причина отправки на доработку')),
                ('revision_comment', models.TextField(blank=True, verbose_name='Комментарий после доработки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('under_review', 'На согласовании'), ('rejected', 'Отправлена на доработку'), ('approved', 'Согласована'), ('in_progress', 'Выполняется'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки на согласование')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата согласования')),
                ('agreed_with', models.ManyToManyField(blank=True, related_name='agreed_events', to='events.employee', verbose_name='С кем были согласованы работы')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL, verbose_name='Согласовал')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создал заявку')),
                ('departments', models.ManyToManyField(blank=True, related_name='events', to='events.department', verbose_name='Подразделения')),
                ('device_types', models.ManyToManyField(blank=True, related_name='events', to='events.devicetype', verbose_name='Тип объекта')),
                ('devices', models.ManyToManyField(blank=True, related_name='events', to='events.device', verbose_name='Объект')),
                ('executors', models.ManyToManyField(blank=True, related_name='executor_events', to='events.employee', verbose_name='ФИО исполнителей')),
                ('joint_workers', models.ManyToManyField(blank=True, related_name='joint_events', to='events.employee', verbose_name='С кем совместно будут проводиться работы')),
                ('notified_persons', models.ManyToManyField(blank=True, related_name='notified_events', to='events.employee', verbose_name='Кто был оповещён о работах')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_events', to='events.employee', verbose_name='ФИО ответственного')),
            ],
            options={
                'verbose_name': 'Заявка на работы',
                'verbose_name_plural': 'Заявки на работы',
                'ordering': ['-created_at'],
                'permissions': [('can_approve_event', 'Может согласовывать заявки'), ('can_edit_dictionaries', 'Может редактировать справочники')],
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='Файл')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.event', verbose_name='Заявка')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('site', models.CharField(max_length=100, verbose_name='Площадка')),
                ('building', models.CharField(max_length=100, verbose_name='Здание')),
                ('room', models.CharField(max_length=100, verbose_name='Помещение')),
                ('rack', models.CharField(max_length=100, verbose_name='Технологический шкаф')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
                'ordering': ['region', 'site', 'building'],
                'unique_together': {('region', 'site', 'building', 'room', 'rack')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='object_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_events', to='events.location', verbose_name='Место нахождения объекта'),
        ),
        migrations.AddField(
            model_name='event',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_events', to='events.location', verbose_name='Место выполнения работ'),
        ),
        migrations.AddField(
            model_name='event',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.material', verbose_name='Используемые материалы/инструменты'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.organization', verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='event',
            name='object_outside_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_outside_events', to='events.outsidelocation', verbose_name='Место нахождения объекта за территорией Общества'),
        ),
        migrations.AddField(
            model_name='event',
            name='work_outside_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_outside_events', to='events.outsidelocation', verbose_name='Место выполнения работ за территорией Общества'),
        ),
        migrations.AddField(
            model_name='event',
            name='affected_services',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.service', verbose_name='Затронутые сервисы'),
        ),
        migrations.AddField(
            model_name='event',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.unit', verbose_name='Отделы/лаборатории/цехи/участки'),
        ),
        migrations.CreateModel(
            name='TechCardStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Номер шага')),
                ('planned_start', models.DateTimeField(verbose_name='Планируемая дата и время начала шага')),
                ('planned_end', models.DateTimeField(verbose_name='Планируемая дата и время окончания шага')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_card_steps', to='events.event', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Шаг технологической карты',
                'verbose_name_plural': 'Шаги технологической карты',
                'ordering': ['event', 'step_number'],
                'unique_together': {('event', 'step_number')},
            },
        ),
    ]
