# Generated by Django 6.1.1 on 2026-09-09 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actual_disruption_duration_days',
            field=models.IntegerField(default=0, verbose_name='Фактическая длительность перерыва (дни)'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_disruption_duration_hours',
            field=models.IntegerField(default=0, verbose_name='Фактическая длительность перерыва (часы)'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_disruption_duration_minutes',
            field=models.IntegerField(default=0, verbose_name='Фактическая длительность перерыва (минуты)'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_disruption_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время окончания перерыва'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_disruption_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время начала перерыва'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_duration_days',
            field=models.IntegerField(default=0, verbose_name='Фактическая длительность (дни)'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_duration_hours',
            field=models.IntegerField(default=0, verbose_name='Фактическая длительность (часы)'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_duration_minutes',
            field=models.IntegerField(default=0, verbose_name='Фактическая длительность (минуты)'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время окончания работ'),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата и время начала работ'),
        ),
        migrations.AddField(
            model_name='event',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='event',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения работ'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Работы завершены'),
        ),
        migrations.AddField(
            model_name='event',
            name='work_done',
            field=models.TextField(blank=True, verbose_name='Что было сделано'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('action_type', models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('delete', 'Удаление'), ('view', 'Просмотр'), ('submit', 'Отправка на согласование'), ('approve', 'Согласование'), ('reject', 'Отправка на доработку'), ('complete', 'Завершение'), ('cancel', 'Отмена'), ('export', 'Экспорт'), ('login', 'Вход'), ('logout', 'Выход')], max_length=20, verbose_name='Тип действия')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=50, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Представление объекта')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Изменения')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Путь запроса')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='events_audi_created_6d9fb2_idx'), models.Index(fields=['user', 'created_at'], name='events_audi_user_id_1c4bd3_idx'), models.Index(fields=['action_type', 'created_at'], name='events_audi_action__833af3_idx')],
            },
        ),
    ]
