# Generated by Django 6.1.1 on 2026-09-10 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_actual_disruption_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_event', 'Может согласовывать заявки'), ('can_edit_dictionaries', 'Может редактировать справочники'), ('can_manage_users', 'Может управлять пользователями')], 'verbose_name': 'Заявка на работы', 'verbose_name_plural': 'Заявки на работы'},
        ),
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_cards', to='events.event', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Технологическая карта',
                'verbose_name_plural': 'Технологические карты',
                'ordering': ['event', 'name'],
            },
        ),
    ]
