# Generated by Django 6.1.1 on 2026-09-10 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_techcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcardstep',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Содержание шага'),
        ),
        migrations.AlterField(
            model_name='techcardstep',
            name='step_number',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Порядок'),
        ),
    ]
