# Generated by Django 6.1.1 on 2026-09-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_techcardstep_name_alter_techcardstep_step_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='techcardstep',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='techcardstep',
            name='step_number',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AddConstraint(
            model_name='techcardstep',
            constraint=models.UniqueConstraint(fields=('event', 'step_number'), name='unique_step_number_per_event'),
        ),
    ]
